// <auto-generated />
namespace WebSales___WebForms_e_EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SellerAndSalesRecord_ChangeVariable_DisplayFormat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SellerAndSalesRecord_ChangeVariable_DisplayFormat));
        
        string IMigrationMetadata.Id
        {
            get { return "202109241550222_SellerAndSalesRecord_ChangeVariable_DisplayFormat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
